<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>CasCadeVR.Works.Services.Tests</RootNamespace>
	<AssemblyName>Works.Services.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Works.Context.Tests\Works.Context.Tests.csproj" />
    <ProjectReference Include="..\Works.Repository\Works.Repository.csproj" />
    <ProjectReference Include="..\Works.Services\Works.Services.csproj" />
  </ItemGroup>

</Project>
