<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<RootNamespace>CasCadeVR.Works.Entities</RootNamespace>
	<AssemblyName>Works.Entities</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Works.Context.Contracts\Works.Context.Contracts.csproj" />
  </ItemGroup>

</Project>
