<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>CasCadeVR.Works.Services</RootNamespace>
	<AssemblyName>Works.Services</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Works.Repository.Contracts\Works.Repository.Contracts.csproj" />
    <ProjectReference Include="..\Works.Services.Contracts\Works.Services.Contracts.csproj" />
  </ItemGroup>

</Project>
