<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>CasCadeVR.Works.Common</RootNamespace>
	<AssemblyName>Works.Common</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Works.Common.Contracts\Works.Common.Contracts.csproj" />
    <ProjectReference Include="..\Works.Context.Contracts\Works.Context.Contracts.csproj" />
  </ItemGroup>

</Project>
