<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>CasCadeVR.Works.Context.Contracts</RootNamespace>
	<AssemblyName>Works.Context.Contracts</AssemblyName>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.15" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Works.Common.Contracts\Works.Common.Contracts.csproj" />
    <ProjectReference Include="..\Works.Entities.Contracts\Works.Entities.Contracts.csproj" />
  </ItemGroup>

</Project>
