<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<RootNamespace>CasCadeVR.Works.Web</RootNamespace>
	<AssemblyName>Works.Web</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Works.Common\Works.Common.csproj" />
    <ProjectReference Include="..\Works.Context\Works.Context.csproj" />
    <ProjectReference Include="..\Works.Export.Contracts\Works.Export.Contracts.csproj" />
    <ProjectReference Include="..\Works.Export\Works.Export.csproj" />
    <ProjectReference Include="..\Works.Repository\Works.Repository.csproj" />
    <ProjectReference Include="..\Works.Services\Works.Services.csproj" />
    <ProjectReference Include="..\Works.Web.Contracts\Works.Web.Contracts.csproj" />
  </ItemGroup>

</Project>
