<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>CasCadeVR.Works.Repository.Contracts</RootNamespace>
	<AssemblyName>Works.Repository.Contracts</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Works.Entities\Works.Entities.csproj" />
  </ItemGroup>

</Project>
